baseURL = "http://localhost:1313"
languageCode = "en-GB"
title = "Policy Metric"
theme = "PaperMod"

[params]
  env = "production"
  description = "Developing robust measures for decision maing and accountability."
  author = "David Caplan"
  defaultTheme = "light"
  disableThemeToggle = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4